handle value is null for formatNumber
icebob/benchmarkify pull request #7
Opened 2020-09-25 17:57 UTC by zheli-1

possible bug: in the function of "formatNumber" in index.js, when value is null, it throw an unhandle rejection typeerror 

Hi, I was running this benchmarkify to test validator.js with the test case I generated symbolically. It triggered an unhandled rejection type error in formatNumber function. I was wondering if this should be a null value check for this error. It only needs a simple fix(see my pull request please). but if this is a real unhandle error, it would be a finding of the symbolic execution experiment. Please let me know.

exception throwed as below:
![image](https://user-images.githubusercontent.com/32209826/94300451-dfacce00-ff1d-11ea-9eb2-d577e2f9bd98.png)

2020-09-25 19:32 UTC, icebob requested changes
Return with 0 if null is not correct because it gives false value. By the way, should return with string, so please change to `if (value == null) return "-";`

2020-09-28 17:10 UTC, zheli-1 reviewed
Yes, thanks for the correction. Appreciated it. I will send another request. It's a great tool:)

2020-09-30 18:09 UTC, zheli-1 commented
Any updates?

2020-09-30 18:44 UTC, icebob approved these changes
Thanks

2020-09-30 18:49 UTC, closed without merging